-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 19-11-2023 a las 22:50:56
-- Versión del servidor: 10.4.28-MariaDB
-- Versión de PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;S
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `politicaargentina`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `partidospoliticos`
--

CREATE TABLE `partidospoliticos` (
  `partido_id` int(11) NOT NULL,
  `nombrepartido` varchar(100) DEFAULT NULL,
  `ideologia` varchar(100) DEFAULT NULL,
  `aniofundacion` year(4) DEFAULT NULL,
  `lideractual` varchar(255) DEFAULT NULL,
  `sedecentral` varchar(255) DEFAULT NULL,
  `sitioweb` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `partidospoliticos`
--

INSERT INTO `partidospoliticos` (`partido_id`, `nombrepartido`, `ideologia`, `aniofundacion`, `lideractual`, `sedecentral`, `sitioweb`) 
VALUES
(1, 'La Libertad Avanza', 'Libertaria', '2021', 'Javier Milei', 'VIAMONTE 986', 'lalibertadavanza.com.ar'),
(2, 'Juntos por el CAMBIO', 'Republicana', '2019', 'Mauricio Macri', 'DEAN FUNES 228', 'jxc.com.ar'),
(3, 'Unión por la Patria', 'Peronista', '2023', 'Sergio Massa', 'SAN JOSÉ 181', 'porlapatria.org'),
(4, 'Hacemos por Nuestro País', 'Peronista', '2023', 'Juan Schiaretti', 'LA VOZ DEL INTERIOR 7000', 'www.hacemospornuestropais.com'),
(5, 'Frente de Izquierda y de los Trabajadores', 'Izquierdista', '2011', 'Myriam Bregman', 'LA RIOJA 853', 'frentedeizquierda.org'),
(6, 'Principios y Valores', 'Justicialista', '2020', 'Guillermo Moreno', 'CORRIENTES 2510', 'www.principiosyvalores.org'),
(7, 'Movimiento Libres del Sur', 'Socialista Democrática', '2006', 'Jesús Escobar', 'DIRECTORIO 2491', 'https://libresdelsur.org.ar'),
(8, 'Nuevo MÁS', 'Socialista', '2003', 'Manuela Castañeira', 'CHILE 1362', 'www.mas.org.ar'),
(9, 'Movimiento Independiente Juventud Dignidad', 'Estatista', '2021', 'Santiago Cúneo', 'TAPIR 3035', 'www.instagram.com/mijdargentina'),
(10, 'Política Obrera', 'Izquierdista', '2021', 'Marcelo Ramal', 'LA PAMPA 5820', 'junta-politicaobrera.ar'),
(11, 'Frente Patriota Federal', 'Derecha Extremista', '2017', 'César Biondini', 'GAONA 1785', 'www.bv-capital.org'),
(12, 'Movimiento de Acción Vecinal', 'Varias', '2018', 'Raúl Albarracín', 'AYACUCHO 353', 'www.facebook.com/MAVCBA'),
(13, 'Proyecto Joven', 'Izquierdista', '2017', 'Mempo Giardinelli', 'SAN LUIS 935', 'proyectojovenpba.blogspot.com'),
(14, 'Liber.AR', 'Libertaria', '2018', 'Ramiro Vasena', 'SERRANO 1551', 'liber.ar'),
(15, 'Unión del Centro Democrático', 'Socialista', '1982', 'Andrés Passamonti', 'AZCUÉNAGA 1517', 'www.ucede.org'),
(16, 'Unión Cívica Radical', 'Radicalista', '1981', 'Gerardo Morales', 'ADOLFO ALSINA 1786', 'www.ucr.org.ar'),
(17, 'Unión para la Integración y el Resurgimiento', 'Nacionalista', '1982', 'Alberto Assef', 'HUMBERTO I° 2087', 'www.unirargentina.org'),
(18, 'Aptitud Renovadora', 'Laboralista', '2021', 'Juan Pablo Chiesa', 'DIAZ VELEZ 3730', 'www.jpchiesa.com.ar'),
(19, 'Generación Para un Encuentro Nacional', 'Progresista', '2007', 'Margarita Stolbizer', 'RIVADAVIA 3217', 'www.partidogen.org.ar'),
(20, 'Partido Comunista de Argentina', 'Comunista', '1918', 'Mario Alderete', 'CALLAO 274', 'www.pcce.com.ar'),
(21, 'Partido Socialista', 'Socialista', '1986', 'Mónica Fein', 'PERÓN 1751', 'www.partidosocialista.org.ar'),
(22, 'Partido Obrero', 'Trotskismo', '1982', 'Néstor Pitrola', 'BARTOLOMÉ MITRE 2162', 'www.po.org.ar'),
(23, 'Partido Intransigente', 'Progresista', '1972', 'Daniel Galdeano', 'RIOBAMBA 482', 'www.pi.org.ar'),
(24, 'Partido Socialista Auténtico', 'Socialista', '2002', 'Mariano Mazziteli', 'SARANDÍ 56', 'www.psa.org.ar'),
(25, 'Partido Demócrata Cristiano', 'Democracia Cristianista', '1954', 'Nancy Alberione', 'COMBATE DE LOS POZOS 1055', 'democraciacristiana.com.ar'),
(26, 'Partido Justicialista', 'Peronismo', '1947', 'Cristina Fernandez de Kirchner', 'MATHEU 130', 'www.partidojusticialista.org.ar'),
(27, 'Partido De Jubilados Pensionados Y Retirados De Mendoza', 'Jubiladista', '2019', 'Edgardo Civit Evans', '9 DE JULIO 2294', 'www.facebook.com/profile.php?id=100068609954168'),
(28, 'Partido INTEGRAR', 'Liberalista', '2017', 'Ramiro Marra', 'RECONQUISTA 575', 'integrarargentina.org'),
(29, 'Partido Federal', 'Federalista', '1973', 'Julio Cruciani', 'AV. DE MAYO 962', 'partidofederal.ar'),
(30, 'Movimiento Socialista de los Trabajadores', 'Socialista', '1992', 'Celeste Fierro', 'PERÚ 439', 'www.mst.org.ar');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `politicos`
--

CREATE TABLE `politicos` (
  `politico_id` int(11) NOT NULL,
  `nombre` varchar(100) DEFAULT NULL,
  `apellido` varchar(100) DEFAULT NULL,
  `cargo` varchar(100) DEFAULT NULL,
  `partido_id` int(11) DEFAULT NULL,
  `educacion` varchar(255) DEFAULT NULL,
  `fechanacimiento` date DEFAULT NULL,
  `biografia` text DEFAULT NULL,
  `imagen` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `politicos`
--

INSERT INTO `politicos` (`politico_id`, `nombre`, `apellido`, `cargo`, `partido_id`, `educacion`, `fechanacimiento`, `biografia`, `imagen`) 
VALUES
(1, 'Javier', 'Milei', 'Diputado', 1, 'Universidad de Belgrano', '1970-10-22', 'Javier Gerardo Milei es un economista, ejecutivo, político y docente argentino, líder del espacio político La Libertad Avanza. Comúnmente es definido por medios de comunicación internacionales como un político de extrema derecha, en tanto que medios nacionales argentinos y consultores políticos de ese país lo describen como de derecha libertaria. Es seguidor de los postulados formulados por los economistas de la escuela austriaca,​ y se autodenomina como anarcocapitalista en la teoría, liberal-libertario y minarquista en la vida real, aunque varias de sus posiciones políticas han sido descritas como conservadoras o ultraconservadoras.', 'https://www.cronista.com/files/image/358/358891/613e99f3a2bab_360_202!.webp?s=2add1c06c58502d3a9dd0d3f4297fb1c&d=1689799849&oe=jpg'),
(2, 'Carolina', 'Piparo', 'Diputada', 1, 'Universidad del Salvador', '1976-09-12', 'Carolina Rosana Píparo​ es una trabajadora social y política argentina que actualmente ocupa el cargo de diputada nacional por la provincia de Buenos Aires por el bloque “Buenos Aires Libre”. Además, fue diputada provincial por Cambiemos y ocupó el cargo de Secretaria de Asistencia a la Víctima y Políticas de Género de la Municipalidad de La Plata.', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Carolina_P%C3%ADparo.png'),
(3, 'Victoria', 'Villaruel', 'Diputada', 1, 'Universidad de Buenos Aires', '1975-04-13', 'Victoria Eugenia Nair Villarruel es una abogada, escritora, activista y política argentina que actualmente ocupa el cargo de diputada nacional. Ha sido descrita como una política ultraconservadora. Es una de las firmantes de la Carta de Madrid, un documento liderado por el partido político de extrema derecha español Vox. Es fundadora de la asociación civil autodenominada Centro de Estudios Legales sobre el Terrorismo y sus Víctimas, la cual ella preside desde sus inicios.', 'https://cnnespanol.cnn.com/wp-content/uploads/2023/05/Victoria-Villarruel.jpg?quality=100&strip=info'),
(4, 'Ramiro', 'Marra', 'Legislador', 1, 'Universidad del Salvador', '1982-11-20', 'Ramiro Daniel Marra es un político, columnista, empresario y youtuber financiero argentino. Es director de Bull Market Group, una empresa fintech perteneciente a su familia. Desde diciembre de 2021 se desempeña como legislador de la Ciudad de Buenos Aires, siendo presidente del bloque de La Libertad Avanza.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ramiro_Marra.jpg/220px-Ramiro_Marra.jpg'),
(5, 'Lucia', 'Montenegro', 'Legisladora', 1, 'Universidad de Buenos Aires', '1994-10-22', 'Lucía Elena Montenegro tiene 26 años y es entrenadora de un arte marcial que creó su padre, el CHAIU DO KWAN. En su Instagram confiesa que ama subirse al ring y a su grupo de combate \"Los dragones\". Se hizo conocida en campaña solo por subir al escenario donde estaba Milei y sin mediar palabra, empezar a arrojar patadas al aire, como en lucha.', 'https://pbs.twimg.com/profile_images/1468368150769111043/Q1JedgC2_400x400.jpg'),
(6, 'Jorge', 'Macri', 'Ministro de Gobierno', 2, 'St. Brendan \'s College', '1965-03-05', 'Jorge Macri es un político y empresario argentino referente de la Propuesta Republicana, un partido político de Argentina que forma parte de la alianza Juntos por el Cambio. Desde el 2 de diciembre de 2021 ocupa el cargo de Ministro de Gobierno de la Ciudad de Buenos Aires y es el actual candidato a Jefe de Gobierno porteño por Juntos por el Cambio.', 'https://media.licdn.com/dms/image/D4D03AQF30hmQM2tHjA/profile-displayphoto-shrink_800_800/0/1689689265075?e=2147483647&v=beta&t=vkpMZlVmIsjBiW5bzrJK1B3QHMmTMXDTT2v0EdQx_Xo'),
(7, 'Patricia', 'Bullrich', 'Presidenta del PRO', 2, 'Universidad de Palermo', '1956-06-11', 'Patricia Bullrich es una política argentina y una de los líderes de la coalición Juntos por el Cambio.​ Fue ministra de Seguridad de la Nación durante la gestión 2015-2019; diputada nacional por la Ciudad Autónoma de Buenos Aires en los períodos 2007-2015 y 1993-1997; ministra de Trabajo entre octubre de 2000 y octubre de 2001; ministra de Seguridad Social entre octubre y noviembre de 2001; y secretaria de Política Criminal entre 1999 y octubre de 2000. Tras superar las elecciones primarias de 2023,​ se convirtió en la candidata a presidente de cara a las elecciones presidenciales del 2023 por parte de la alianza Juntos por el Cambio.', 'https://pbs.twimg.com/profile_images/1632819068636913664/DEKIHYGO_400x400.jpg'),
(8, 'Horacio', 'Larreta', 'Jefe de Gobierno CABA', 2, 'Universidad de Buenos Aires', '1965-08-29', 'Horacio Antonio Rodríguez Larreta es un economista y político argentino, actual jefe de Gobierno de la Ciudad Autónoma de Buenos Aires desde el 10 de diciembre de 2015. Es uno de los principales líderes de la coalición política Juntos por el Cambio. El 9 de diciembre de 2015 asumió como jefe de Gobierno de la Ciudad de Buenos Aires. Fue reelecto en el cargo para un nuevo período en 2019. De la mano del Partido Justicialista, fue gerente general de la ANSES, interventor del PAMI. Fundó el Grupo Sophia para formar líderes políticos y desde ese centro acompañó a Mauricio Macri en la fundación del partido Propuesta Republicana (PRO), que resultó vencedor en las elecciones ejecutivas de la Ciudad de Buenos Aires de 2007, 2011, 2015 y 2019 y en las elecciones presidenciales de 2015.', 'https://www.lanacion.com.ar/resizer/EoI7iFssn9X7FN1J7y3a1o33_bI=/420x0/filters:format(webp):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/XSK6XCLUUBEQTKCZDFEHFZZTY4.png'),
(9, 'Federico', 'Angelini', 'Diputado', 2, 'Universidad Católica Argentina', '1977-02-19', 'Federico Angelini es un licenciado en sistemas y político argentino. Desde el 10 de diciembre de 2019 se desempeña como diputado nacional por la Provincia de Santa Fe y a partir del 14 de abril de 2023 es confirmado como presidente interino del partido Propuesta Republicana tras la licencia de Patricia Bullrich al cargo. Fue el precandidato a vicegobernador en las Elecciones de Santa Fe por Juntos por el Cambio acompañando a Carolina Losada en la fórmula.', 'https://www.lanacion.com.ar/resizer/PrusJFGQ8RHTwq3JhYwYqqQ_Piw=/280x0/filters:format(webp):quality(70)/s3.amazonaws.com/arc-authors/lanacionar/1dc544c3-7300-4a42-a8c8-136614f1faf6.jpg'),
(10, 'Elsia', 'Carrió', 'Diputada', 2, 'Universidad Nacional del Nordeste', '1956-12-26', 'Elisa María Avelina Carrió , ​más conocida como Lilita Carrió, es una abogada, catedrática universitaria y política argentina que se desempeñó como Diputada de la Nación por la Ciudad Autónoma de Buenos Aires desde 2009 hasta 2020, ocupando dicho cargo previamente entre 2005 y 2007. Años antes, fue Diputada de la Nación por la Provincia del Chaco entre 1995 y 2003, Convencional Constituyente en 1994. Es miembro de la coalición Juntos por el Cambio.', 'https://www.fundacionkonex.org/custom/web/data/imagenes/repositorio/2018/06/29/13703/201806290155115be8a7b32a49a70f697ec3deb6e0fa98.jpg'),
(11, 'Sergio', 'Massa', 'Ministro de Educación', 3, 'Universidad de Belgrano', '1972-04-22', 'Sergio Tomás Massa es un abogado y político argentino, miembro de Unión por la Patria, anteriormente denominada Frente de Todos, actual coalición política de tendencia peronista y progresista gobernante en Argentina desde 2019. Fue miembro y presidente de la Cámara de Diputados de la Nación desde 2019 hasta 2022. Es fundador y líder del Frente Renovador, fuerza integrante de la coalición política Frente de Todos que se impuso en la elección presidencial de 2019. Desde agosto de 2022 ocupa el cargo de ministro de Economía de la Nación. Durante su mandato como ministro la inflación interanual superó el 100% por primera vez desde 1990.', 'https://pbs.twimg.com/profile_images/1639607611036188675/ER1KQEWf_400x400.jpg'),
(12, 'Cristina', 'Kirchner', 'Vicepresidenta', 3, 'Universidad Nacional de la Plata', '1953-02-19', 'Cristina Elisabet Fernández de Kirchner es una política y abogada argentina, presidenta de la Nación Argentina entre el 10 de diciembre de 2007 y el 9 de diciembre de 2015,​ diputada provincial por la provincia de Santa Cruz entre 1989 y 1995 y diputada y senadora nacional por las provincias de Santa Cruz y Buenos Aires en los periodos 1995-2007 y 2017-2019. Desde el 10 de diciembre de 2019 se desempeña como vicepresidenta de la Nación Argentina. Es miembro de la coalición política Unión por la Patria.', 'https://www.biografiasyvidas.com/biografia/f/fotos/fernandez_kirchner.jpg'),
(13, 'Agustin', 'Rossi', 'Jefe de Gabinete', 3, 'Universidad Civil de Rosario', '1959-10-18', 'Agustín Óscar Rossi es un ingeniero civil y político argentino. Fue miembro de la Cámara de Diputados de la Nación desde el 2005 hasta el 2013 y desde el 2017 hasta el 2019. Comenzando en política en la ciudad de Rosario como concejal entre 1987 y 1991, y entre 2002 y 2005, fue ministro de Defensa de la Nación (2013-2015, 2019-2021), diputado nacional por su provincia natal (2005-2013, 2017-2019), siendo jefe de la bancada oficialista del Frente para la Victoria en ambos periodos, candidato a gobernador de Santa Fe en 2011, y director de la Agencia Federal de Inteligencia entre 2022 y 2023. Desde el 15 de febrero de 2023 ejerce como jefe de Gabinete de Ministros de la Nación. El 23 de junio de 2023 se presentó como candidato a vicepresidente junto a Sergio Massa por Unión por la Patria en las elecciones presidenciales de 2023.', 'https://fotos.perfil.com/2022/11/09/trim/900/900/agustin-rossi-1450451.jpg'),
(14, 'Eduardo', 'Pedro', 'Ministro del Interior', 3, 'Universidad de Buenos Aires', '1976-11-11', 'Eduardo Enrique de Pedro, conocido como Wado de Pedro, es un abogado y político argentino, ministro del Interior de la Nación desde el 10 de diciembre de 2019. Antes fue diputado nacional por la provincia de Buenos Aires desde 2015 a 2019. Fue vicepresidente de Aerolíneas Argentinas y uno de los directivos de Telecom Argentina.', 'https://pbs.twimg.com/profile_images/1567512437334704128/pFMJ-CN6_400x400.jpg'),
(15, 'Juana', 'di Tullio', 'Senadora', 3, 'Escuela de Psicología Social Pichon Riviere', '1971-10-22', 'Juliana di Tullio es una psicóloga social​ y política argentina. Desde 2005 a 2017 fue diputada nacional por la Provincia de Buenos Aires. Entre mayo de 2013 y diciembre de 2015 fue presidenta del bloque del Frente para la Victoria durante la presidencia de Cristina Fernández de Kirchner.​ Se graduó como licenciada en psicología social e integró además el Parlamento del Mercosur.​ Actualmente es senadora nacional por la provincia de Buenos Aires del Frente de Todos.', 'https://pbs.twimg.com/profile_images/676519234244124674/k4uUtH8V_400x400.jpg'),
(16, 'Juan', 'Schiaretti', 'Gobernador de Córdoba', 4, 'Universidad Nacional de Córdoba', '1949-06-19', 'Juan Schiaretti es un contador público, subteniente de reserva del Ejército y político argentino, integrante del Partido Justicialista y del peronismo federal. Desde el 10 de diciembre de 2015, se desempeña como gobernador de la provincia de Córdoba, cargo que ya había ocupado desde 2007 hasta 2011. Además, desempeñó los cargos de secretario de Comercio e Industria de la Nación Argentina, diputado de la Nación Argentina en tres oportunidades, gobernador de Santiago del Estero en calidad de interventor federal y ministro de Producción y vicegobernador de la provincia de Córdoba.', 'https://www.cba.gov.ar/wp-content/uploads/2022/10/Juan-Schiaretti.jpg'),
(17, 'Florencio', 'Randazzo', 'Diputado', 4, 'Universidad de Buenos Aires', '1964-03-01', 'Aníbal Florencio Randazzo es un político y contador público argentino. Entre 2007 y 2015 se desempeñó en el gabinete de Cristina Fernández de Kirchner, primero como ministro del Interior de la Nación y más tarde como ministro del Interior y Transporte, ya que esta última área fue incorporada al ministerio que venía administrando. Previamente se había desempeñado como ministro de Gobierno y jefe de Gabinete de Ministros de la provincia de Buenos Aires, durante la gobernación de Felipe Solá.', 'https://media.licdn.com/dms/image/C4D03AQFm8WlSrHp0Dg/profile-displayphoto-shrink_800_800/0/1517456059388?e=2147483647&v=beta&t=3HzXRKqN3h4YtwHIjTt7NPW54BvIznPpBDKX_IQO9D4'),
(18, 'Jose', 'Antonio', 'Presidente del Partido Autonomista', 4, 'Universidad Nacional del Nordeste', '1941-02-25', 'José Antonio Romero Feris, conocido como “Pocho” Romero Feris, es un abogado político y presentador argentino. Diputado Provincial en 1965 y Presidente de la Cámara de Diputados de la Provincia de Corrientes. Ejerció el mandato de Gobernador de Corrientes entre 1983 y 1987. Seguidamente fue Senador Nacional, hasta 2001, y en 2019 fue precandidato a la presidencia de la Nación.', 'https://www.diariodecuyo.com.ar/export/sites/diariodecuyo/img/2019/08/11/f7p7_crop1565504518674.jpg_302442289.jpg'),
(19, 'Hilda Chiche', 'Duhalde', 'Candidata a diputada', 4, 'Instituto Hammer', '1946-10-14', ' Política y docente argentina, ex primera dama y ex senadora por el Partido Peronista. Está casada con Eduardo Duhalde, expresidente de la Nación.', 'https://imgsvr.radiocut.site/get/crop/center/200/200/cuts_logos/b4/b8/b4b8b3a8-24bf-4ae7-a781-105aa9d4667a.jpg'),
(20, 'Diego', 'Bossio', 'Candidato a diputado', 4, 'Universidad de Buenos Aires', '1979-09-09', ' Político y economista argentino. Fue director ejecutivo de la ANSES entre 2009 y 2015 durante la presidencia de Cristina Fernández de Kirchner. Fue diputado nacional por la provincia de Buenos Aires por el Bloque Justicialista.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/DiegoBossio.jpg/1200px-DiegoBossio.jpg'),
(21, 'Nicolas', 'del Caño', 'Diputado', 5, 'Universidad Nacional de Cuyo', '1980-02-06', 'Nicolás del Caño es un político argentino. Es un exdirigente estudiantil y actualmente dirigente nacional del Partido de los Trabajadores Socialistas, partido de orientación trotskista por el que ha sido electo dos veces como diputado nacional y candidato a presidente por el Frente de Izquierda y de los Trabajadores en 2015 y 2019.', 'https://pbs.twimg.com/profile_images/1427366044595855363/mxI1Jy6b_400x400.jpg'),
(22, 'Myriam', 'Bregman', 'Diputada', 5, 'Universidad de Buenos Aires', '1972-02-25', 'Myriam Teresa Bregman es una abogada, activista y política argentina. Es dirigente nacional del Partido de los Trabajadores Socialistas (PTS).2​ Fue diputada nacional por la provincia de Buenos Aires desde 2015 hasta 2016. Candidata a vicepresidenta de la Nación Argentina por el Frente de Izquierda y de Trabajadores - Unidad, secundando en la fórmula a Nicolás del Caño en las elecciones de 2015, legisladora de la Ciudad Autónoma de Buenos Aires desde 2017 hasta 2021 y nuevamente diputada nacional desde diciembre de 2021.', 'https://pbs.twimg.com/media/EBstFvTXUAAPVKm.jpg'),
(23, 'Raul', 'Godoy', 'Diputado', 5, 'Hospital Universitario de Albacete', '1965-11-16', 'Raúl Godoy desde 1994 trabaja en la fábrica bajo control obrero Zanon de Neuquén. Es parte de la agrupación que recuperó la comisión interna y posteriormente el sindicato. Fue secretario general en ese primer mandato y luego volvió a trabajar a la producción en Zanon rotando desde su lugar en el sindicato, hecho inédito desde la década de los 70. Es fundador del Partido de los Trabajadores Socialistas y fue diputado provincial por el FIT en Neuquén. Al finalizar su mandato rotó en la banca y volvió a su puesto en la fábrica, desde donde encabeza la pelea por las empresas recuperadas ceramistas y de todo el país.', 'https://www.pts.org.ar/IMG/moton299.png?1595524832'),
(24, 'Noelia', 'Agüero', 'Legisladora', 5, '', '1980-05-25', 'Legisladora Córdoba Izquierda Socialista/ FIT Unidad Delegada gremial, Dirigente de la agrupación Docentes en Marcha y de Izquierda Socialista. Integrante de Isadora, mujeres en lucha. Activista de Ambiente en Lucha.', 'https://izquierdasocialista.org.ar/2020/media/k2/items/cache/addeb2c7f51816c0213ea42dd06e5a88_L.jpg?t=20220114_174717'),
(25, 'Marcela', 'Almeida', '', 5, '', '0000-00-00', '', 'https://www.ctacapital.org/wp-content/uploads/almeida.jpg'),
(26, 'Guillermo', 'Moreno', 'Candidato a presidente por elpartido Principios y Valores', 6, 'Universidad Argentina de la Empresa', '1955-10-15', 'empresario, político y economista argentino, secretario de comunicaciones entre 2003 y 2006, y de Comercio Interior desde el 2006 hasta el 2 de diciembre de 2013. Tras dejar ese cargo, fue agregado económico de la embajada argentina en Italia.Conduce el partido político Principios y Valores,​ fuerza política que se autodefine como peronista. A pesar de su inhabilitación, de cara a las elecciones de 2023 manifestó públicamente su decisión de presentarse como candidato a presidente por dicho partido. ', 'https://pbs.twimg.com/profile_images/1567508237661995011/BFGZjhuS_400x400.jpg'),
(27, 'Leonardo', 'Fabre', 'Candidato a vicepresidente por el partido Principios y Valores', 6, '', '1950-01-01', 'Secretario General de la Asociación del Personal de los Organismos de Previsión Social (APOPS / ANSES).', 'https://www.codigobaires.com.ar/adjuntos/800/codigoba/2023/06/image-108.png'),
(28, 'Pablo', 'Maron Challu', 'Precandidato a parlamentario del mercosur Distrito Nacional', 6, '', '1943-01-01', 'Economista, asesor de la Coordinadora de las Industrias de Productos Alimenticios (COPAL) y Director Ejecutivo de la Cámara Industrial de Laboratorios Farmacéuticos Argentinos (CILFA). Se desempeñó en cargos de dirección en diferentes compañías alimenticias, metalúrgicas y farmacéuticas.', 'https://www.continentalcorrientes.com/multimedia/imagenes/fotos/2023-07-06/872774_grande.jpg'),
(29, 'Maria', 'Colombo', 'Diputada', 6, '', '1957-01-17', 'Su militancia se inició con Abelardo Ramos en el último año de la escuela secundaria, en la que era presidenta del Centro de Estudiantes de la Escuela Sarmiento (escuela primaria y secundaria dependiente de la Universidad Nacional de Tucumán) Desde el peronismo se incorporo a la política en la ciudad de Buenos Aires, manteniendo pertenencia en el Sindicato de Amas de Casa, para recuperar una bandera de Evita expuesta en La Razón de mi Vida, otorgar a la mujer. En esa dirección crea, el SACRA el 12 de marzo de 1983 con las consignas: salario, obra social y sindicato para las amas de casa.', 'https://www.agenciapacourondo.com.ar/sites/www.agenciapacourondo.com.ar/files/styles/destacado/public/2023-08/pimpi.jpg?itok=l1iHEXhm'),
(30, 'Claudio', 'Heredia', 'Legislador', 6, 'Universidad de Buenos Aires', '1964-01-01', 'Claudio Domingo Heredia es abogado, profesor de Derecho Penal en la Universidad de Buenos Aires y en la Universidad Kennedy y asesor legal de la Dirección Ejecutiva del PAMI.Generación Malvinas, participó de la movilización del 30 de marzo de 1982 por el paro nacional de Ubaldini, a los dos días se produce Malvinas en plena dictadura. Se introduce al peronismo a través de su padre y luego militando en la universidad', 'https://parlamentaria.legislatura.gob.ar/uploads/imagenes/legislador/M_23fa24c6-d6eb-4bb5-b65f-c1df61f351b4.jpg'),
(31, 'Humberto', 'Tumini', 'Presidente del Partido', 7, 'Universidad Nacional de Cordoba', '1949-10-29', 'Humberto Miguel Tumini es un dirigente político y exfuncionario argentino. Actualmente es el presidente del Movimiento Libres del Sur.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Humberto_Tumini_lanz%C3%B3_su_pre-candidatura_a_Presidente.png/220px-Humberto_Tumini_lanz%C3%B3_su_pre-candidatura_a_Presidente.png'),
(32, 'Jesus', 'Escobar', 'Secretario del partido', 7, 'Universidad Nacional de Comahue', '1972-02-10', 'Jesús Escobar nació el 10 de febrero de 1971 en El Maitén, Chubut, y a los dos años su familia se mudó a Neuquén. Pasó su infancia en El Huecú, localidad del norte neuquino, su adolescencia en la localidad de Cutral Co y con la finalidad de estudiar una carrera universitaria se instaló definitivamente en Neuquén Capital. Cursó hasta cuarto año de Ingeniería Civil en la Universidad Nacional del Comahue.', 'https://libresdelsur.org.ar/wp-content/uploads/escobar-300x300-1.jpg'),
(33, 'Silvia', 'Saravia', 'Coordinadora Nacional de Barrios de Pie', 7, '', '0000-00-00', 'Docente, educadora popular, deportista en su juventud.', 'https://libresdelsur.org.ar/wp-content/uploads/saravia.1-300x300-1.jpg'),
(34, 'Marianella', 'Lezama', 'Concejala de la Ciudad Capital de Santiago del Estero', 7, '', '1994-01-01', 'Contadora Pública Nacional. Comenzó su militancia en el año 2010 en el movimiento universitario Sur en la Universidad Nacional de Santiago del Estero-Desde el años 2012 es Coordinadora Provincial de Mumalá (Mujeres de la Matria Latinoamericana). Actualmente es Concejala de la Ciudad Capital de Santiago del Estero', 'https://libresdelsur.org.ar/wp-content/uploads/hid_300x300.jpg'),
(35, 'Jorge', 'Ceballos', 'Coordinador de VIAS Sarmiento', 7, 'Universidad Nacional de Córdoba', '1960-08-22', 'Nació en Villa María, Córdoba, el 22 de agosto de 1960. Es abogado. Se radicó en San Justo, Partido de La Matanza desde 1988. Es uno de los fundadores del Movimiento Libres del Sur y uno de sus principales referentes en la Provincia de Buenos Aires. A los 21 años, en 1981, comenzó a militar en el ámbito juvenil del Partido Intransigente de Córdoba y fue electo Secretario General por el Comité Capital en 1987. Estudió en la Universidad Nacional de Córdoba donde se recibió de abogado. A mediados de 1988 se radicó en la provincia de Buenos Aires y empezó a caminar sus barrios. Trabajó como abogado en 1989, en San Justo, partido de La Matanza , vinculando su profesión desde el primer momento con el ámbito social. Defendió y formó parte de numerosos procesos de lucha vinculados a casos de gatillo fácil y de despidos laborales por causas sindicales y políticas. Trabajó por y entre los sectores más humildes de los barrios asesorando, en forma gratuita, a las personas y organizaciones con necesidad de ayuda jurídica. Ejerció la docencia en escuelas públicas (1990-1995) y fue co-presidente de la Asamblea Permanente por los Derechos Humanos (APDH) de La Matanza. De ese vivir y hacer, en medio de la propia necesidad y construcción de los sectores populares del país, nació el movimiento social Barrios de Pie, en el año 2001. Desde entonces y hasta 2004 fue su coordinador nacional. Fue fundador de la Corriente Patria Libre (1987) y del Movimiento Libres del Sur (2006). En el ámbito público se desempeñó desde junio del 2004 como Director Nacional de Asistencia Comunitaria en el Ministerio de Desarrollo Social de la Nación, siendo designado en el año 2006 como Subsecretario de Organización y Capacitación Popular en la misma cartera, cargo al que renunció cuando Libres del Sur decidió alejarse del kirchnerismo, en diciembre de 2008', 'https://libresdelsur.org.ar/wp-content/uploads/Ceballos_300x3001.jpg'),
(36, 'Manuela', 'Castañeira', 'Dirigente del partido', 8, 'Universidad de Buenos Aires', '1984-11-22', 'Sociologa, activista feminista y política argentina nacida en Paraná Entre Rios. Se desempeña en puesto no docente en la Unsam. Se postuló a presidenta por primera vez en 2015', 'https://www.tiempoar.com.ar/wp-content/uploads/2021/05/3afafbbaf0f437712a4a5be883d13704_BIG.jpg'),
(37, 'Federico', 'Winokur', 'Dirigente nacional del partido y Acción ecológica Anticapitalista', 8, 'Universidad de Buenos Aires', '1992-09-16', 'Con 28 años es el precandidato a primer diputado nacional más joven de la elección porteña. También ejerce la docencia.', 'https://media.minutouno.com/p/4b595749ae24cb593f419cc2c9212211/adjuntos/150/imagenes/039/189/0039189097/imagepng.png?0000-00-00-00-00-00'),
(38, 'Marina', 'Hidalgo Robles', 'Candidata al Parlasur', 8, 'Universidad de Buenos Aires', '0000-00-00', 'Socialista y feminista abolicionista, luchadora por los derechos de las mujeres, niños y niñas. Comenzó en la politica haciendo voluntariados en la provincia de Santa Fe. Hace diez años trabaja enla Dirección de la Niñez en la Ciudad', 'https://pbs.twimg.com/profile_images/1677768202623893506/C_p9XAGK_400x400.jpg'),
(39, 'Violeta', 'Alonso', 'Tercera precandidata a la legislatura porteña acompañando a Federico WinoKur', 8, 'Universidad de Buenos Aires', '1998-01-01', 'En el secundario fue miembro del Centro de Estudiantes del Colegio Nacional Buenos Aires. Es trabajadora Social en niñez adolescencia.Actualmente es Secretaria Gral. del Centro de Estudiantes  de la Facultad de Filosofía y Letras', 'https://izquierdaweb.com/wp-content/uploads/2022/04/WhatsApp-Image-2022-04-12-at-10.33.38-PM.jpeg'),
(40, 'Lucas Manuel', 'Ruiz', 'Precandidato a Vicepresidente', 8, '', '1983-01-01', 'Docente Neuquino, profesor de Historia. Referente del gremio ATEN Asociación de trabajadores de la educación de Neuquén. Integrante de la Agrupación Carlos Fuentealba', 'https://pbs.twimg.com/profile_images/1672668346091728897/xLYCptys_400x400.jpg'),
(41, 'Raul', 'Castells', 'Coordinador Nacional del Movimiento Izquierda Juventud Dignidad', 9, '', '1953-12-12', 'Farmacéutico, dirigente social y político. A comienzos de la década de 1990 fundó junto a su segunda esposa, Nina Pelozo, el Movimiento Independiente de Jubilados y Desocupados (MIJD).Castells se ha caracterizado por sus acciones de alto impacto en los medios de comunicación, como la ocupación a la fuerza de sucursales de McDonald\'s y supermercados', 'https://media.radio10.com.ar/p/0b4bd632fcdcd32f421c69e892fc61bf/adjuntos/220/imagenes/040/351/0040351117/1200x675/smart/raul-castellsjpg.jpg'),
(42, 'Santiago', 'Cuneo', '', 9, '', '1970-09-05', 'empresario, político y periodista, conocido por el programa periodístico \"Uno Mas Uno Tres\" que se transmitió por radio como por televisión desde el 2013 hasta el 2018. ', 'https://www.infobae.com/new-resizer/QhbneylKZd2bkQY_e2x5U8l5PaM=/filters:format(webp):quality(85)/cloudfront-us-east-1.images.arcpublishing.com/infobae/B74MADCKHJHH3PW7NRB2EAZZPY.jpg'),
(43, 'Horacio', 'Ricciardelli', '', 9, '', '0000-00-00', 'Lider del Movimiento Cívico Militar Cóndor. Ricciardelli es un Vice Comodoro de la Fuerza Aérea Argentina en situación de retiro', 'https://scontent.faep14-2.fna.fbcdn.net/v/t39.30808-6/308739368_529775665814624_1275315447080455167_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHacOnJNwmUOLVaCvNNny3Wd0iop4AQ_qt3SKingBD-qyn9N0AFp3Pv0hkFbFg8BzjYn41DKCms9ITP0ALJSIgd&_nc_ohc=MC652GFm'),
(44, 'Gustavo', 'Barranco', '', 9, '', '1962-04-30', '', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmdRfpNz_2-Kbky5IEPztE-FuxwUlii7G7Ui3qdLfyTH16PTVP8Mo7lhM9gDsCCdYI43A&usqp=CAU'),
(45, 'Chinda Concepción', 'Brandolino', 'Diputada', 9, 'Universidad Nacional de La Plata', '1954-06-03', 'Estudió Medicina en la Universidad Nacional de La Plata y fue perito médico legista hasta 2013. En 2015 fue candidata a diputada nacional por el Partido Todos por Buenos Aires. Se hace llamar “La mujer de la ola celeste”, por manifestar su oposición a la legalización del aborto durante el debate sobre el tema en el Congreso en 2018.', 'https://www.infoblancosobrenegro.com/uploads/noticias/5/2020/08/chinda-1.jpg'),
(46, 'Marcelo', 'Ramal', 'precandidato a parlamentarios del Mercosur', 10, 'Universidad de Buenos Aires', '1954-10-13', 'Lic. Licenciado en Ciencias Económicas, profesor universitario y político trotskista argentino. Se desempeña como docente en las Universidades Nacionales de Buenos Aires y Quilmes.Profesor Adjunto de la materia Organización Industrial en la Facultad de Ciencias Económicas de la Universidad de Buenos Aires. Allí, partiendo de un enfoque marxista desarrolla una revisión de otras teorías económicas.​', 'https://scontent.faep14-2.fna.fbcdn.net/v/t39.30808-6/238830493_2995479757336927_8411313492004458358_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeGg94SLL3TV01T8BDUcK6cB6JbCuonQhFDolsK6idCEUPo5niCAj1pdH-DWfsHHpuw6lho13C99fWHqj9FQtYqI&_nc_ohc=mJPrKwJ'),
(47, 'Jorge', 'Altamira', 'Legislador', 10, '', '1942-04-14', 'José Saúl Wermus conocido por su seudónimo Jorge Altamira, es un político argentino, miembro fundador y dirigente de Política Obrera y el Partido Obrero (PO). Fue legislador porteño durante el período 2000-2004 y candidato a presidente de la nación en cinco oportunidades.Fue director del periódico semanal Prensa Obrera y de la revista teórica En defensa del marxismo, ambos editados por el Partido Obrero. Escritor prolífico, ha publicado diversos libros y folletos', 'https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2019/06/12153529/altamira.jpg'),
(48, 'Juan Carlos', 'Giordano', 'Diputado', 10, '', '1962-01-01', 'Es abogado y político argentino, dirigente del partido Izquierda Socialista integrante de la Unidad Internacional de los Trabajadores - cuarta Internacional (UIT-CI). Es el actual director del periódico El Socialista y fue diputado nacional por el Frente de Izquierda y de los Trabajadores en dos ocasiones, a través del acuerdo de rotación de dicho frente.', 'https://izquierdasocialista.org.ar/2020/media/k2/items/cache/58d202aaaa2189ef38d9ee41e6c06249_XL.jpg?t=20220111_193101'),
(49, 'Graciela ', 'Calderon', 'Senadora', 10, '', '1962-12-08', ' Graciela Beatriz Calderon nació en La Matanza, Provincia de Buenos Aires, el 8 de diciembre de 1962. Es Docente. Entre 1994 y 2006, ocupó un cargo de orientadora educacional, en la Dirección General de Cultura y Educación. Es una histórica dirigente de Izquierda Socialista. Fue Secretaria General adjunta del SUTEBA La Matanza.Electa en 2021, como Diputada Provincial, en la lista del Frente de Izquierda, tercera sección, encabezada por Guillermo Kane. Renunció en abril de 2023 en el marco de la rotación de bancas del FIT, siendo reemplazada por Laura Cano.', 'https://admin.lanoticia1.com/sites/default/files/graciela_calderon_0.jpg'),
(50, 'Soledad', 'Capurro', 'Sebadira', 10, 'Universidad Nacional de Cuyo', '1986-06-01', 'Soledad Sosa Capurro es trabajadora del Poder Judicial de Mendoza, donde volvió una vez terminado su mandato como diputada nacional. Entre los judiciales es reconocida por la lucha en defensa de los trabajadores tanto en sus condiciones de trabajo, como por su salarios. Como parte de esta actividad fue una de las fundadoras de la Agrupación Naranja Judicial, que se destaca por plantear la independencia política tanto de la Corte Suprema de Justicia, como del gobierno y los partidos patronales, tambien es activista por los derechos de la mujer', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/SoledadSosaPic.jpg/1200px-SoledadSosaPic.jpg'),
(51, 'Raul', 'Albarracin', 'Candidato a presidente de la nación', 11, '', '1960-02-20', 'Abogado. Legislador de la provincia de Córdoba', 'https://www.lavoz.com.ar/resizer/wBDkmDQUjNYG1fJUMRJFMokGWAI=/980x640/smart/filters:quality(75):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/MROBGEDPFNAJJPDEA5HP326BJQ.jpg'),
(52, 'Sergio Dario', 'Pastore', 'Apoderado del Movimiento de Acción Vecinal', 11, 'Instituto de Desarrollo Económico y Social', '1966-09-25', 'Abogado, oriundo de La Cumbre, Córdoba', 'https://www.lavoz.com.ar/resizer/ftu8bqmtNGC2ngOJvqULwKnW3Q4=/980x640/smart/filters:quality(75):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/F3O72KGL6JCS3B3LOJZWISDG7U.jpg'),
(53, 'Fernando Jose Ortega', '', '', 11, '', '0000-00-00', '', 'https://www.argentina.gob.ar/sites/default/files/2023/08/57_a_movimiento_de_accin_vecinal.pdf'),
(54, 'Martin', 'Dandach', 'Presidente del partido', 11, 'Universidad Nacional de Córdoba', '0000-00-00', 'Abogado, estudió en la Universidad Nacional de Córdoba', 'https://pbs.twimg.com/profile_images/1614858640673984512/YPoRNV_A_400x400.jpg'),
(55, 'Alejandra', 'Durán', '', 11, '', '0000-00-00', 'Alejandra Fernández de Durán lucha contra la inseguridad desde que Ian fue asesinado en 2002. Hoy es candidata a vicegobernadora por Movimiento de Acción Vecinal. Aceptó ser candidata a vicegobernadora y ocupar el segundo lugar en la lista de legisladores', 'https://lajornadaweb.com.ar/wp-content/uploads/2019/08/Paso-2019-Alejandra-Fern%C3%A1ndez-696x928.jpeg'),
(56, 'Cesar', 'Biondini', 'Apoderado y Secretario General', 12, '', '1983-01-13', 'es abogado y dirigente nacionalista argentino. Hijo del Líder Nacionalista Alejandro Carlos Biondini, fue dos veces candidato a Legislador por la Ciudad Autónoma de Buenos Aires. En las elecciones legislativas de octubre del año 2005, encabezó la lista de Legisladores porteños en un frente electoral denominado Acción Ciudadana. Para las elecciones de junio del 2009, encabezó la nómina del Partido Alternativa Social (Lista 300), fuerza predecesora de Bandera Vecinal.', 'https://pbs.twimg.com/profile_images/1674241722807644160/Mm1R9tsb_400x400.jpg'),
(57, 'Mariel', 'Avendaño', '', 12, '', '1971-08-20', 'Docente en Económicas, Administradora de empresas', 'https://imgsvr.radiocut.site/get/thumb/600/600/cuts_logos/76/40/76408810-7eb2-4847-90c9-96d0165b36dc.jpg'),
(58, 'Victor Omar', 'Faloni', '', 12, '', '0000-00-00', '', 'https://www.argentina.gob.ar/sites/default/files/2023/08/95_a_frente_patriota_federal.pdf'),
(59, 'Enrique Carlos', 'Venturino', '', 12, '', '1944-01-17', 'Teniente coronel retirado, fue uno de los cabecillas del levantamiento carapintada de 1987. Fue uno de los fundadores del Movimiento por la Dignidad y la Independencia (MODIN) de orientación derechista, junto a Aldo Rico y el exmayor del Ejército Ernesto Barreiro', 'https://nuevodiarioweb1.cdn.net.ar/252/nuevodiarioweb/images/01/42/46/1424656_109d436ff2c6b35ea2dd347b04f849af45d03ffd5d09e1890853fdb75c6c2dcc/xs.jpg'),
(60, 'Pedro Fabián', 'Llanos', 'Precandidato a concejal', 12, '', '0000-00-00', '', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsjqxxfcf6ki29z8L9zZTojZZyofpUafWCaFbwQ0-qAgnRiPtcUzNzGPpG4lJE1XcH0hM&usqp=CAU'),
(61, 'Martin Miguel', 'Ayerbe Ortiz', 'precandidato a presidente', 13, '', '1976-03-19', '', 'https://scontent.faep24-2.fna.fbcdn.net/v/t39.30808-6/358579136_738878381578907_4390219735077878298_n.jpg?_nc_cat=1&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHqkRYmqge6FLJLiPVHO6LKH08Iqa0kYfgfTwiprSRh-MJm4l1JgfXpvd9NYp03I06ZZAKRpc6mCayCPdbcq0ZQ&_nc_ohc=c5U9SENizW'),
(62, 'Hugo Mauricio Ezequiel', 'Rodriguez', 'precandidato a vicepresidente', 13, '', '1987-09-19', '', 'https://media.licdn.com/dms/image/D4D03AQFDHZ6XkVfjDg/profile-displayphoto-shrink_200_200/0/1688073043878?e=1706140800&v=beta&t=g7pc2qkEyGk8sBOH7Qr7hLzd6c2QYPTfmDsNtNNH64Q'),
(63, 'Romina Valeria', 'Cortaberria', 'Diputada', 13, '', '0000-00-00', '', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE0WNVzBbZz6GgV5SCvru6Ru8mFZaYeuQqcFogCY5gTg&s'),
(64, 'Mempo', 'Giardinelli', 'precandidato a presidente', 13, 'Universidad Nacional del Nordeste', '1947-02-08', 'Oscar Alfredo Ramón Giardinelli, ​ es un escritor y periodista argentino. Traducido a 26 idiomas, fue galardonado con el Premio Rómulo Gallegos en 1993 en Venezuela y recibió también diversos premios en México, España, Italia y Chile. Preside una fundación dedicada al fomento de la lectura.', 'https://www.fundacionkonex.org/custom/web/data/imagenes/repositorio/2020/09/14/16318/202009140711280415d7189eb5668870d43a035a28e692.jpg'),
(65, 'Reina Xiomara', 'Ibañez', 'precandidata a presidenta', 13, '', '1991-12-07', 'Empezó a militar a los 14 años y estuvo en dos partidos, pero sintió que no le hacían lugar. Después llegó al Movimiento Independiente de Justicia y Dignidad (MIJD), que conduce Raúl Castells, de donde también se fue. Hoy tiene 31 años y es la primera mujer trans en anotarse para ser presidenta. Se postula por el partido de izquierda Proyecto Joven.', 'https://www.elciudadanoweb.com/wp-content/uploads/2017/05/p04f1-sc-1.jpg'),
(66, 'Nazareno', 'Etchepare', 'precandidato a presidente', 14, 'Universidad del Salvador', '1975-10-09', 'Abogado, Columnista opinión Perfil.com ', 'https://pbs.twimg.com/profile_images/1700615737952350208/KaYOxiSM_400x400.jpg'),
(67, 'Santiago David', 'Valenzuela', 'precandidato a vicepresidente', 14, '', '0000-00-00', '', 'https://media.licdn.com/dms/image/C4E03AQF6J8MHAqpwjA/profile-displayphoto-shrink_800_800/0/1603893717146?e=2147483647&v=beta&t=LFDEqKScf1kG6y0sWOzvHzMJRlkvFZF6bze6fAwyKfQ'),
(68, 'Julio', 'Barbaro', 'Precandidato a presidente de la nación', 14, 'Universidad del Salvador', '1942-01-29', 'Escritor, pensador, profesor y político argentino asociado al peronismo. Es licenciado en Ciencias Políticas por la Universidad del Salvador. Fue diputado nacional (1973-1976), secretario de Cultura de la Nación (1989-1991) durante la presidencia de Carlos Menem, e interventor del Comité Federal de Radiodifusión -COMFER- (2003-2008),​ durante las presidencias de Néstor Kirchner y Cristina Fernández.​ Al finalizar su mandato como interventor del COMFER continuó su labor de intelectual escribiendo libros y artículos para publicaciones periódicas, y se destaca su columna semanal en Infobae. Actualmente afiliado al Frente Liber.Ar', 'https://fotos.perfil.com/2023/05/25/trim/987/555/julio-barbaro-1575256.jpg?webp'),
(69, 'Ramona', 'Pucheta', 'Precandidata a vicepresidente de la nación', 14, '', '1964-11-10', 'Es una política y activista social argentina. Entre 2011 y 2015 fue diputada nacional por la provincia de Buenos Aires.', 'https://fotos.perfil.com/2014/10/02/trim/987/555/ramona-pucheta-voto-a-favor-del-nuevo-codigo-civil-pero-despues-no-supo-explicar-partes-fundamentales-del-proyecto-1002-g1.jpg?webp'),
(70, 'Miguel Angel', 'Lacour', 'precandidato parlamentario del Parlasur', 14, '', '0000-00-00', 'Médico Cirujano. Profesor universitario. Especialista en Otorrinolaringología, Alergia y Administración Hospitalaria.', 'https://www.todoprovincial.com/wp-content/uploads/2023/07/WhatsApp-Image-2023-07-17-at-21.34.53-1-e1689944455894.jpeg'),
(71, 'Andres', 'Passamonti', 'Legislador', 15, 'Universidad del Salvador', '0000-00-00', 'Dirección Provincial de Política Criminal Provincia de Buenos Aires. Legislatura Ciudad Autónoma de Buenos Aires. Consejo de Emergencia de la Ciudad Autónoma de Buenos Aires (Secretaría de Emergencias)', 'https://fotos.perfil.com/2023/06/29/trim/987/555/andres-passamonti-ucede-1-g20230629-1599568.jpg?webp'),
(72, 'Pamela', 'Fernandez Margaride', 'candidata a vicepresidenta', 15, '', '1979-10-09', '', 'https://pbs.twimg.com/profile_images/1674735751743823873/F1Tcp0sw_400x400.jpg'),
(73, 'Oscar Dario', 'Zaffaroni', 'candidato concejal titular', 15, '', '0000-00-00', 'empresario inmobiliario y martillero ', 'https://unoarrecifes.com/wp-content/uploads/2021/08/Oscar-Zaffaroni.jpg'),
(74, 'Yanina Marcela', 'Calccia', ' candidata concejal titular', 15, '', '0000-00-00', '', 'https://scontent.faep24-2.fna.fbcdn.net/v/t39.30808-6/239495164_118856483831469_7539300398675141286_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHOtZqu8onVNZ265_IxnbpxqZ5hz_FqJJWpnmHP8WoklWzDTzF4e38w4LJvCEaSVyg0oVi3bXR3kr4yr_PmQKgf&_nc_ohc=XCVfI6o9'),
(75, 'Carlos', 'Boyadjian', 'candidato a concejal', 15, '', '0000-00-00', 'empresario y dirigente de Fenorba y de la Cámara de Comercio e Industria ', 'https://unoarrecifes.com/wp-content/uploads/2022/04/Carlos-Boyadjian.jpg'),
(76, 'Pablo', 'Blanco', 'Senador', 16, 'Universidad de la Patagonia Derecho Bancario', '1953-06-06', 'Pablo Daniel Blanco es un contador, banquero y político radical argentino que ejerce como Senador Nacional en representación de la provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur. Previamente ocupó varios cargos en la administración fueguina, fue legislador provincial en cuatro ocasiones y convencional constituyente al momento de redactarse la constitución de la provincia.', 'https://pbs.twimg.com/profile_images/1249102127936335874/34knX2sI_400x400.jpg'),
(77, 'Mario', 'Negri', 'Diputado', 16, 'Universidad Nacional de Córdoba', '1954-02-06', 'Mario Raúl Negri es un abogado y político argentino que ocupa el cargo de diputado nacional por la provincia de Córdoba. Actualmente preside el bloque de diputados de la Unión Cívica Radical y es presidente del interbloque parlamentario Juntos por el Cambio. Es su quinto período como diputado.', 'https://rest.hcdn.gob.ar/intra/proxy/parlamentaria/fotos/autoridades/20109929175'),
(78, 'Martín', 'Arjol', 'Diputado', 16, 'Universidad Nacional de Misiones', '1981-07-02', 'Martin Alfredo Arjol es un abogado y político perteneciente al partido de la Unión Cívica Radical, ex presidente del Comité Posadas. Se desempeñó como miembro del Jurado de Enjuiciamiento de la Provincia de Misiones, representando al Colegio de Abogados. Fue docente de la Universidad Nacional de Misiones (UNaM) y la Universidad Gastón Dachary. Fue Concejal de la Ciudad de Posadas hasta el año 2021. Actualmente es Miembro de la Cámara de Diputados de la Nación Argentina.', 'https://rest.hcdn.gob.ar/intra/proxy/parlamentaria/fotos/autoridades/20288182516'),
(79, 'Marcos', 'Carasso', 'Diputado', 16, 'Universidad Nacional de Cordoba', '1970-01-19', 'Marcos Gustavo Carasso es intendente en uso de licencia en la localidad de General Cabrera. Diputado nacional en ejercicio desde 2021 y, a su vez, presidente de la Unión Cívica Radical de Córdoba.', 'https://rest.hcdn.gob.ar/intra/proxy/parlamentaria/fotos/autoridades/20214053587'),
(80, 'Stella', 'Olalla', 'Senadora', 16, 'Instituto Nacional de Enseñanza Superior de Paraná', '1943-03-07', 'Stella Maris Elisa Olalla es una docente y política argentina de la Unión Cívica Radical, que se desempeña como senadora nacional por la provincia de Entre Ríos desde 2019.', 'https://media.elentrerios.com/fotos-v2/2020/03/13/l_1584108148.jpg'),
(81, 'Alberto', 'Asseff', 'Presidente del partido', 17, '1942-10-31', '0000-00-00', 'Diputado Nacional, docente y abogado', 'https://rest.hcdn.gob.ar/intra/proxy/parlamentaria/fotos/autoridades/20043949323'),
(82, 'Raul Atilio', 'Frassinelli', '', 17, '', '0000-00-00', '', ''),
(83, 'Susana', 'Sanchez Morteo', 'Apoderada', 17, '', '0000-00-00', '', ''),
(84, 'Virginia', 'Luna', 'Secretaria general', 17, '', '0000-00-00', '', 'https://www.eltiempo.com/files/image_640_428/files/crop/uploads/2017/07/02/59599741d4890.r_1499059460498.0-117-3000-1620.jpeg'),
(85, 'Mathiu', 'Hernan', 'Apoderado', 17, '', '0000-00-00', '', 'https://media.licdn.com/dms/image/C4E03AQGTRSmHpGMnWg/profile-displayphoto-shrink_400_400/0/1578077883102?e=2147483647&v=beta&t=M7lMLtImqOqDdCLtRsQRuU0It1AvvCUQFwvjtSaTF9M'),
(86, 'Juan Pablo', 'Chiesa', '', 18, '', '1980-01-01', 'Abogado laboralista, docente, escritor, especialista en empleo y políticas públicas', 'https://media.licdn.com/dms/image/D4D03AQGIN1F3OlCjyw/profile-displayphoto-shrink_800_800/0/1695133909620?e=2147483647&v=beta&t=mErn5pqrgHVCrsWJI7X1qxE6Vf_2H2Uqkp29mmj7yqo'),
(87, 'Fabio', 'Onetto', '', 18, '', '0000-00-00', 'Periodista y político', 'https://scontent.faep24-1.fna.fbcdn.net/v/t1.6435-9/132391038_152007156677340_2010888921740387635_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=810d5f&_nc_eui2=AeHWNRjkilrrtuyDRSA9Et1jZSlYX8glCW1lKVhfyCUJbYGzFKGMLtWN4j0DnMu5vb5RI-pNtWrSB4ftfOzkGGuY&_nc_ohc=1biggogMEi'),
(88, 'Delfina', 'wagner Meza', 'Diputada', 18, '', '2003-01-01', 'candidata a diputada porteña y recientemente fue señalada por la vicepresidenta Cristina Krichner por el atentado en su contra ocurrido el 1º de septiembre de 2022. Se dio a conocer en los medios por su relación con el ex participante de “Gran Hermano” Walter”Alfa”', 'https://instagram.faep24-1.fna.fbcdn.net/v/t51.2885-15/358052885_218776851121034_7749346307581027932_n.jpg?stp=dst-jpg_e35_p1080x1080&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE4MDAuc2RyIn0&_nc_ht=instagram.faep24-1.fna.fbcdn.net&_nc_cat=102&_nc_o'),
(89, 'Camila Ayelen', 'Pita', '', 18, '', '0000-00-00', 'Abogada', 'https://media.licdn.com/dms/image/C4D03AQFhA-jcYCASWg/profile-displayphoto-shrink_800_800/0/1562951504769?e=2147483647&v=beta&t=e79YGDqrHo-XNVyDcQVblMsUTmdVcrsK1ogH6SixO3I'),
(90, 'Nabilla Soraya', 'Khoder', 'Diputada', 18, '', '0000-00-00', 'Abogada, escritora', 'https://instagram.faep24-2.fna.fbcdn.net/v/t51.2885-15/370886604_6803290859715368_1833297958196885109_n.webp?stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi43MjB4OTAwLnNkciJ9&_nc_ht=instagram.faep24-2.fna.fbcdn.net&_nc_cat=108&_nc_ohc=Uanh1UOl7'),
(91, 'Margarita', 'Stolbizer', 'Diputada', 19, 'Universidad de Morón', '1955-03-17', 'política y abogada argentina.​ Lidera el Partido GEN, el cual fundó en 2007 tras abandonar la Unión Cívica Radical', 'https://yt3.googleusercontent.com/ytc/APkrFKb-xpPBex5zF2jIO26oFNZ_W84117d_PvMHRK0cFQ=s900-c-k-c0x00ffffff-no-rj'),
(92, 'Sergio', 'Abrevaya', 'Presidente del partido', 19, 'Universidad de Buenos Aires', '1963-07-11', 'Abogado y político argentino perteneciente al Partido GEN que actualmente se desempeña como legislador en la Legislatura de la Ciudad Autónoma de Buenos Aires.​​ Mediador en ejercicio desde 1996. Fue creador y coordinador de los programas de \"Mediación Comunitaria\" y \"Escolar\" de la Ciudad de Buenos Aires, y Director Nacional de Mediación. Autor de numerosas publicaciones y del libro “Mediación prejudicial”; coautor de “Facilitación en Políticas Públicas” y “Diálogos Apreciativos: el Socio construccionismo en acción ', 'https://parlamentaria.legislatura.gob.ar/uploads/imagenes/legislador/M_504c09a9-80a4-4114-86a5-e05b2bc8d6ee.JPG'),
(93, 'Doris Fátima', 'Mansilla', 'Vicepresidenta del partido', 19, '', '0000-00-00', 'Legisladora de Cordoba', 'https://legislaturacba.gob.ar/wp-content/uploads/2020/06/Mansilla.jpg'),
(94, 'Gonzalo', 'Toselli', 'Secretario general', 19, '', '0000-00-00', 'Intendente de Sunchales', 'https://media.licdn.com/dms/image/C4D03AQE2jf_DtDO_dw/profile-displayphoto-shrink_800_800/0/1645360340503?e=2147483647&v=beta&t=ibjA1kAOHbXARo8xHQP9NY_x0KBATCDGsAL-JFsaxQ4'),
(95, 'Silvana Cecilia', 'Arruti', 'Secretaria de Finanzas y Tesorería', 19, '', '0000-00-00', 'Miembro de Asociación Civil \"Bajo La Lupa\" ', 'https://www.genbuenosaires.org.ar/wp-content/uploads/2012/07/vocales_001_Silvana-Arruti.jpg'),
(96, 'Juan', 'Alderete', 'Diputado', 20, '', '1952-09-19', 'Juan Carlos Alderete es un político y dirigente social argentino. Es líder de la C.C.C y dirigente nacional del PCR. En el 2019 asumió como diputado nacional por la Provincia de Buenos Aires, en reemplazo de Eduardo de Pedro, dentro de la lista del Frente de Todos. Su figura tomó notoriedad con las movilizaciones piqueteras ocurridas en la crisis económica de fines de los años noventa.', 'https://www.rionegro.com.ar/wp-content/uploads/2021/09/juan-carlos-alderete-entrevista-neuquen.jpg?w=920&h=517&crop=1'),
(97, 'Carlos', 'Tcholakian', 'Vicepresidente del partido', 20, '', '0000-00-00', 'Militante Comunista. Bostero y rockero. ', 'https://www.elmensajerodiario.com.ar/wp-content/uploads/2011/01/4577_aaaaaa.JPG'),
(98, 'Victor', 'Gorodeki Kot', 'Secretario General', 20, '', '1944-01-01', '', 'https://pbs.twimg.com/profile_images/1389011900709711875/bHmWT-73_400x400.jpg'),
(99, 'Jorge Alberto', 'Kreiness', 'Secretario de Relaciones Internacionales', 20, '', '0000-00-00', 'Periodista, analista de politica internacional', 'https://cnnespanol.cnn.com/wp-content/uploads/2023/06/FireShot-Capture-657-secretario-de-Relaciones-Internacionales-del-Partido-Comunista-Jorge_-www.google.com_.png?w=537&h=351&crop=1'),
(100, 'Tania', 'Caputo', 'Militante del partido Comunista en el Frente de Todos', 20, '', '0000-00-00', 'Concejal del Partido Comunista - FdT HCD ZárateMama de Matilda Licenciada en Trabajo Social Militante Feminista', 'https://i0.wp.com/www.diariolavozdezarate.com/wp-content/uploads/2021/06/tania.jpg?w=288&ssl=1'),
(101, 'Enrique', 'Estevez', 'Diputado', 21, 'Universidad Nacional de Rosario', '1983-05-12', 'Enrique Eloy Estévez Boero es un político argentino del Partido Socialista, que se desempeña como diputado nacional por la provincia de Santa Fe desde 2019, integrando el interbloque Federal.', 'https://enriqueestevez.com.ar/wp-content/uploads/2020/08/IMG_E7722-scaled-e1600219684510.jpg'),
(102, 'Mónica', 'Fein', 'Diputada', 21, 'Universidad Nacional de Rosario', '1957-06-03', 'Mónica Haydée Fein es una política y bioquímica argentina, perteneciente al Partido Socialista. Desde 2011 hasta 2019 fue intendenta de la ciudad de Rosario.', 'https://rest.hcdn.gob.ar/intra/proxy/parlamentaria/fotos/autoridades/27115479968'),
(103, 'Roy', 'Cortina', 'Diputado', 21, 'Universidad de Buenos Aires', '1964-03-14', 'Robert Vincent Cortina (Nueva York, 14 de marzo de 1964), más conocido como Roy Cortina, es un político argentino perteneciente al Partido Socialista con actuación en la Ciudad de Buenos Aires. Desde el 10 de diciembre de 2015 se ha desempeñado como legislador en la Legislatura Porteña en el cargo de tercer vicepresidente. Fue diputado nacional desde 2007 hasta 2015. El Partido Socialista de la Ciudad de Buenos Aires, que preside, desde 2007 ha mantenido una política de alianzas electorales con la Unión Cívica Radical, que en 2019 se ha ampliado a PRO y la Coalición Cívica ARI.', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Roy_CortinaLegislatura.jpg'),
(104, 'Clara', 'Garcia', 'Diputada', 21, '', '1960-05-06', 'Diputada provincial de Santa Fe. Nació en Rosario. Inició su carrera política en 1986 en el Partido Socialista. Ocupó diversos cargos en la Municipalidad de Rosario hasta que en 2009 resultó electa concejal. Asumió como diputada provincial en 2019 donde preside el interbloque Frente Progresista Cívico y Social.', 'https://media.cdn.puntobiz.com.ar/072023/1689871809949.webp?cw=984&ch=553&extw=jpg'),
(105, 'Carolina', 'Losada', 'Vicepresidente del Senado de la Nación Senadora Nacional por la Provincia de Santa Fe ', 21, '', '1972-12-16', 'Carolina Losada es una política​ y panelista argentina. Es conocida por haber sido la conductora de América Noticias y Te cuento al mediodía, y por desempeñarse como panelista en los programas periodísticos \"Intratables y Basta Baby. Actualmente es senadora nacional en representación de la provincia de Santa Fe', 'https://cnnespanol.cnn.com/wp-content/uploads/2021/10/carolina.jpg?quality=100&strip=info');

INSERT INTO `politicos` (`politico_id`, `nombre`, `apellido`, `cargo`, `partido_id`, `educacion`, `fechanacimiento`, `biografia`, `imagen`) 
VALUES
	(106, 'Nestor', 'Pitrola', 'Principal dirigente del Partido Obrero', 22, '', '1952-04-01', 'Fue elegido Diputado Nacional por la provincia de Buenos Aires en las elecciones de 2013 y 2015.', 'https://po.org.ar/wp-content/uploads/2023/05/Nestor-Pitrola-1-e1683724465837.jpg'),
(107, 'Vanina', 'Biasi', 'Candidata a Jefa de Gobierno', 22, '', '0000-00-00', 'Diputada electa FIT-U. Luchadora por los derechos de las mujeres. Delegada gremial de APUBA • Es x izquierda.', 'https://po.org.ar/wp-content/uploads/2023/05/Vanina-Biasi-1-e1683724403894.jpg'),
(108, 'Jessi', 'Gentile', 'Candidata a Vicejefa de Gobierno', 22, '', '0000-00-00', 'Activista ambiental', 'https://periodismodeizquierda.com/wp-content/uploads/2022/02/JESSI-GENTILE.png'),
(109, 'Cele', 'Fierro', 'Diputada', 22, '', '0000-00-00', 'Diputada electa en CABA por el FIT-Unidad - MST', 'https://www.el-libro.org.ar/wp-content/uploads/2019/04/cele.fierro-1-400x280-400x280.jpg'),
(110, 'Alejandro', 'Lipcovich', 'Candidato a Legislador', 22, '', '0000-00-00', 'Delegado de la Junta Interna de ATE Hospital Garrahan ', 'https://po.org.ar/wp-content/uploads/2023/09/Ale-Lipco.jpg'),
(111, 'Daniel', 'Galeano', 'Presidente Interino', 23, '', '0000-00-00', '', 'https://pbs.twimg.com/media/FKHTNFYXMAUQIlR.jpg'),
(112, 'Adriana', 'Diaz', 'Vicepresidente del partido', 23, '', '0000-00-00', ' Licenciada en Comunicación Social. Milita desde sus 19 años en el Partido Intransigente Argentina (PI) y llegó a ser la primera mujer en presidirlo. Actualmente ejerce su segundo mandato como Diputada provincial en la Legislatura de Catamarca. Fue una de las primeras legisladoras en expresarse sobre la despenalización del aborto y la autora de las adhesiones a las leyes de Educación Sexual Integral y Micaela García.', 'https://www.catamarcactual.com.ar/u/fotografias/fotosnoticias/2019/12/23/179809.jpg'),
(113, 'Emilio', 'Ramirez', 'Secretario General', 23, '', '0000-00-00', '', 'https://www.lapatria.com/sites/default/files/styles/ampliar_945/public/noticia/2023-10/Mart%C3%ADn%20Emilio%20Ram%C3%ADrez%20Cardona.jpg?itok=DFq77EuX'),
(114, 'Damian', 'Recalde', 'Secretario del partido', 23, '', '0000-00-00', 'Concejal', 'https://2.bp.blogspot.com/-4lHbplS9nFs/XOBfVjVdF3I/AAAAAAABBlE/VzpXlJIPZsgOPZIV0ump_sOrnD752DqFQCLcBGAs/s1600/32a86d0a-fe58-4fee-ba20-4cb64beff99d.jpg'),
(115, 'Laura', 'Saldivar', 'Concejal', 23, '', '0000-00-00', '', 'https://4.bp.blogspot.com/-mdoPLRCA2dw/XN3AdvhnYsI/AAAAAAABBdw/xHgzx5S7HqEFtOxeoRZZ4PwqIWVoE37RwCLcBGAs/s1600/076270b2-975d-442c-8951-eeff8e272b47.jpg'),
(116, 'Mario', 'Mazzitelli', 'Dirigente Secretaría de Organización', 24, '', '1956-08-17', 'En 1971, bajo la dictadura de Alejandro Lanusse, a la edad de 14 años, concurrió a la Casa del Pueblo, sita en Sarandí 56 de la Ciudad Autónoma de Buenos Aires donde conoció a Enrique Inda, Héctor Polino y Alicia Moreau de Justo. Acordó con la propuesta política y se afilió al Partido Socialista Argentino. ,En el 2011 fue candidato a Diputado Nacional por la Provincia de Buenos Aires. ', 'https://scontent.faep14-2.fna.fbcdn.net/v/t39.30808-6/273524333_355512116392826_4383126911761955102_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_ohc=os4arGXk7lIAX-XVIuM&_nc_ht=scontent.faep14-2.fna&oh=00_AfDh0HOl1jlU4-c10PvBSIqiIshapHhUvMkHsjOaDKzALQ&oe=6'),
(117, 'Leandro Nicolás', 'Bonaura', 'Secretario general', 24, '', '0000-00-00', 'Docente de formaciónCon experiencia en el sector de asesoría política. Cargos electivos propios y asesoramiento a legisladores. Actualmente, representante comercial de Empresa de Turismo y responsable de redes y comunicación', 'https://scontent.faep14-3.fna.fbcdn.net/v/t39.30808-6/259447911_10226133987196696_1458702026369517042_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=5f2048&_nc_ohc=rUP5HJBbqOIAX8vpsie&_nc_ht=scontent.faep14-3.fna&oh=00_AfB_-dsaRgg2W-_E_Aj6qBGcgda-WAFSWm87v-4SAvfccQ&oe'),
(118, 'Carlos Alberto', 'De Marco', 'Secretario Gremial', 24, '', '0000-00-00', 'Carlos Alberto De Marco, presidente de la Junta de Custodios de Alcohólicos Anónimos de Argentina.', 'https://img.lagaceta.com.ar/fotos/notas/2019/07/18/600x400_812621_201907171756360000001.webp'),
(119, 'Eduardo', 'Andriotti Romani', 'Secretario del interior', 24, '', '0000-00-00', 'Abogado Litigante en Estudio juridico Romanin,Mar del Plata, Buenos Aires ', 'https://scontent.faep14-3.fna.fbcdn.net/v/t39.30808-6/376791078_828483488654695_6907203491322672118_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=5f2048&_nc_ohc=AWdn-PG1m6cAX-tDvdG&_nc_ht=scontent.faep14-3.fna&oh=00_AfCfiOLbqW5G87p74ZsNVW-f-sPO-ek0BhDPxTHHGCmAog&oe=6'),
(120, 'Guadalupe', 'Castaño Salgado', 'Secretaria de la juventud', 24, '', '0000-00-00', '', 'https://media.licdn.com/dms/image/D4D03AQFJhGwqYlNBDg/profile-displayphoto-shrink_200_200/0/1693937425656?e=1700092800&v=beta&t=C8QQiAgj_AhFuVYqDzggkom2t-rd1F0Y5oZkj8sbido'),
(121, 'Carlos Lionel', 'Traboulsi', 'Secretario de relaciones internacionales y apoderado', 25, '', '1960-01-06', 'Abogado.Diplomado en Relaciones Internacionales. Vicepresidente Alterno Cono Sur Organización Demócrata Cristiana de América (ODCA). Presidente Fundación Argentina Azul.', 'https://media.licdn.com/dms/image/C4E03AQGaykjHcJ2mZQ/profile-displayphoto-shrink_200_200/0/1516800467130?e=2147483647&v=beta&t=nhBJMx2rOCSPSy8C9NVf3xqjAMOntdyGukwnfwBQWiw'),
(122, 'Silvina Lorena', 'Ripolli', 'Diputada', 25, '', '0000-00-00', 'Importante experiencia en los Derechos del Consumidor, trabaje mas de 12 años en diferentes sectores gubernamentales con esta temática. Importante experiencia en Negociación, Mediación y Conciliaciones, evitando el litigio empresarial. ', 'https://media.licdn.com/dms/image/D4D03AQFMUPj8QD45Lw/profile-displayphoto-shrink_800_800/0/1663621891123?e=2147483647&v=beta&t=B7mI2oZc_b4ePt5OMy8NSbc-9oEx0Oeq9vggafvSUs0'),
(123, 'Fernando Gustavo', 'Szlajen', '', 25, '', '1968-09-05', 'Es un rabino y académico argentino-israelí especializado en el campo de la bioética. Es actualmente Profesor titular de posgrado e investigador en bioética en la Universidad de Buenos Aires; en metodología de la investigación en la Universidad Nacional de la Matanza y en la Universidad Nihon Gakko; y en historia social y política del judaísmo en la Pontificia Universidad Católica Argentina. Se desempeñó como Director de AMIA Cultura (2015-2023) en la Asociación Mutual Israelita Argentina (AMIA),1 generando y gestionando numerosos proyectos culturales y educativos.', 'https://media.licdn.com/dms/image/C5603AQF0C8DYxbWw3Q/profile-displayphoto-shrink_200_200/0/1517736231114?e=2147483647&v=beta&t=nN0TzBKG5XkdDQz5kv7waYB3QyGIi3gttcevvuJYF3g'),
(124, 'Florencia Any', 'Markarian', '', 25, '', '0000-00-00', 'Abogada. Derecho Previsional Jubilaciones y Pensiones Reajustes Regímenes especiales: trabajadores portuarios, petroleros, docentes, mineros, altas calorías, etc.', 'https://media.licdn.com/dms/image/D4D03AQHy83DZ1NI36A/profile-displayphoto-shrink_800_800/0/1681686479541?e=2147483647&v=beta&t=2W1sNiT7-I0F5zCvQP2Sg6Rqb_UlEsP2YNNtGbqr9Fs'),
(125, 'Gustavo Agustín', 'Díaz Noblega', 'secretario', 25, '', '0000-00-00', 'Abogado, Es secretario de organización del Partido Demócrata Cristiano CABA mandato 2019-2022', 'https://scontent.faep24-1.fna.fbcdn.net/v/t39.30808-6/293455750_399601038868998_1881577843765769152_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHkmtZAOIQuHZ2I0_txkCvwPDrvC6UqomM8Ou8LpSqiY-acBG9d6VfMcezgyv4mvr3WaL9VlBpOo58LKVYwqrCo&_nc_ohc=ln4h3CjD'),
(126, 'Maximo', 'Kirchner', 'Presidente del partido', 26, 'Universidad Nacional de La Plata', '1977-02-16', 'Maximo Carlos Kirchner es un político y diputado nacional argentino, hijo de los expresidentes Néstor Kirchner y Cristina Fernández de Kirchner.Realizó sus estudios secundarios en el colegio República de Guatemala de esa ciudad. En la ciudad de Buenos Aires estudió durante unos meses periodismo y luego abogacía; pero no concluyó ninguna de las dos carreras.​ En 2006 fundó la organización política juvenil La Cámpora, que lideró en sus comienzos. En diciembre del 2021 asume la presidencia del partido Justicialista.', 'https://medios.uner.edu.ar/wp-content/uploads/2022/11/maximo-1200x675.jpg'),
(127, 'Verónica María', 'Magario', 'Vicepresidenta primera', 26, 'Universidad de Buenos Aires', '1960-05-26', ' Matemática, profesora y política argentina. Se desempeñó como intendenta del partido de La Matanza desde 2015 hasta 2019, y como diputada nacional por la provincia de Buenos Aires desde 2013 hasta 2015.Ejerció como docente y es profesora de matemáticas. Comenzó la licenciatura en Matemáticas en la UBA, con la intención de ir al Instituto Balseiro, ya que quería ser física nuclear. Luego desistió, cuando ya trabajaba en la Cámara de Diputados. Allí empezó su carrera como delegada gremial de la Asociación del Personal Legislativo (APL).​ ', 'https://www.genteba.com/wp-content/uploads/2022/06/Vero%CC%81nica-Magario-01.jpg{'),
(128, 'Melina Mariel', 'Fernández', 'Vicepresidenta segunda', 26, '', '1977-06-12', 'Es una dirigente política argentina que se desempeña como intendenta del partido de Moreno desde el 10 de diciembre de 2019. A fines de los años 1990 comenzó a armar emprendimientos de asistencia social en el territorio. Junto a su esposo y otros compañeros, fundó un comedor y luego estableció el Centro Cultural La Chicharra, un espacio de actividades educativas y recreativas. En 2005, este centro se incorporó al Movimiento Evita, para acceder a la posibilidad de formar cooperativas y ser parte de programas sociales. En 2023 fue reelecta intendenta de Moreno para el período 2023-2027', 'https://www.elteclado.com.ar/fotos/2022/06/27_mariel_fernandez_7.jpg'),
(129, 'Gabriel', 'Kayopodis', 'Secretaría General', 26, 'Universidad de Buenos Aires', '1967-03-06', 'Abogado y político argentino que ocupa el cargo de ministro de Obras Públicas de la Nación Argentina desde el 10 de diciembre de 2019. Entre 2011 y 2019 fue intendente del partido de General San Martín.', 'https://cnnespanol.cnn.com/wp-content/uploads/2023/07/Gabriel-Katopodis.jpg?quality=100&strip=info&w=940&h=530&crop=1'),
(130, 'Omar', 'Plaini', 'Secretario adjunto', 26, '', '1953-05-19', 'Político, sindicalista y dirigente deportivo argentino. Se desempeña como Secretario General del Sindicato de Vendedores de Diarios de Revistas de la Ciudad Autónoma y Provincia de Buenos Aires desde el año 2006 a la actualidad de manera ininterrumpida. Además, desde el año 2023 es presidente del Club Atlético Los Andes. Por otro lado, se desempeñó en tres oportunidades como diputado nacional, entre otros cargos políticos y gremiales.', 'https://images.pagina12.com.ar/styles/focal_3_2_960x640/public/2023-06/742145-5-p1-0.jpg?h=91537187&itok=aVNq7usR'),
(131, 'Edgardo', 'Civit Evans', 'Presidente del partido', 27, 'Universidad Nacional del Litoral', '0000-00-00', 'Ex Director del Banco Hipotecario Nacional', 'https://www.losandes.com.ar/resizer/q0WfzpDjRR3vme0b-TIvw4W4NOo=/300x300/smart/s3.amazonaws.com/arc-authors/grupoclarin/d524edaf-d484-41e1-9b07-5d58e0f982c5.png'),
(132, 'Miguel Hugo', 'Laino', 'Apoderado', 27, '', '0000-00-00', '', 'https://pbs.twimg.com/profile_images/1759795344/miguel_400x400.PNG'),
(133, 'Rolando', 'Frias', '', 27, '', '0000-00-00', '', 'https://www.studbook.org.ar/img/profesionales/66436_6537ce5b04492.png'),
(134, 'Camilo', 'Bustos', '', 27, '', '0000-00-00', '', 'https://media.licdn.com/dms/image/C4D03AQHg7ymdIN4CXQ/profile-displayphoto-shrink_800_800/0/1516622615808?e=2147483647&v=beta&t=j2weToI3V9mwWjozZWxueLadxh6nve6wZ854dfFDYuQ'),
(135, 'Agustin', 'Sanchez Sorondo', 'Apoderado', 27, '', '0000-00-00', '', 'https://media.licdn.com/dms/image/C4D03AQE0TR9E4kukVQ/profile-displayphoto-shrink_800_800/0/1598011596841?e=2147483647&v=beta&t=j1fNfUx1PXxLspBMfS2oDv6_a7-qD8Fg5hY4wzkw61E'),
(136, 'Daniel', 'Amoroso', 'Coordinador nacional', 28, '', '0000-00-00', 'Periodista en Televisión Litotal S.A.. Argentina. Director Nuevos Negocios en ITALIA comunicación. Buenos Aires', 'https://pbs.twimg.com/profile_images/1901725878/image_400x400.jpg'),
(137, 'Mauricio', 'Longing D\'alessandro', 'Vicecoordinador nacional', 28, 'Universidad de Buenos Aires', '1958-08-03', 'Abogado.  Durante la vida universitaria comenzó su actividad política en el Comité Capital de la Unión Cívica Radical. En el marco de las elecciones PASO 2023, D\'Alessandro se presenta como precandidato a Intendente del partido de General San Martín en la lista de Juntos Por El Cambio que lleva como precandidato a Presidente a Horacio Rodríguez Larreta, y como precandidato a Gobernador a Diego Santilli. El 13 de agosto de 2023 triunfó en la interna de JxC confirmando su participación como candidato del partido en las elecciones generales del 22 de octubre de 2023. ', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Mauricio_dalessandro_actualizada.jpg'),
(138, 'Christian', 'López', 'Secretario de acción política', 28, '', '0000-00-00', '', 'https://static.treslineas.com.ar/foto/nota-1707819-christian-lopez-anuncio-importante-visita-bloque-nacional-eeuu-1057297.jpg?imgres=400x0x80'),
(139, 'Alejo', 'Larralde', 'Secretario de desarrollo territorial', 28, '', '0000-00-00', '', 'https://www.notisistema.com/noticias/wp-content/media/2020/11/larralde-610x389.jpg'),
(140, 'Paola', 'Carluccio', 'Secretaria de relaciones parlamentarias', 28, '', '0000-00-00', '', 'https://media.licdn.com/dms/image/C4D03AQF9NOAQg46Ygg/profile-displayphoto-shrink_800_800/0/1541862525627?e=2147483647&v=beta&t=fCsi9cajv5G2LfbjrdgFkoPguG9TS8w0egX5Hu3Ifvk'),
(141, 'Carlos', 'Iannizzotto', '', 29, 'Universidad Nacional del Litoral', '1955-02-12', 'Abogado, profesor y político argentino.​Entre 1997 y 1999 ejerció la Jefatura de Gabinete del Ministerio de Ambiente y Obras Públicas de la provincia de Mendoza.​ Desde 2016 ejerce la presidencia de CONINAGRO. Actualmente, se desempeña como Mediador Familiar y Social por la Universidad de Aconcagua en Mendoza.', 'https://pbs.twimg.com/profile_banners/1424743137549901832/1634655510/600x200'),
(142, 'Adolfo Fausto', 'Inocente', 'Vicepresidente del partido', 29, '', '0000-00-00', '', 'https://www.losandes.com.ar/resizer/qBQpmRfBWEYSJc8D_wSOI1tcoQM=/980x640/smart/filters:quality(75):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/GZSDKZLDHE4DAZJRGMZTGNZWGE.jpg'),
(143, 'Adriana Noemí', 'Delicio', 'Precandidata a Vicegobernadora', 29, '', '0000-00-00', 'Abogada de familia y Laboral', 'https://scontent.faep14-2.fna.fbcdn.net/v/t39.30808-6/300576404_585689346323276_5773227233931939293_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_ohc=hkL_u7S2DVsAX_oHO52&_nc_ht=scontent.faep14-2.fna&oh=00_AfAhWgEfuGAOnDfWO-MepmSutO8DZ2qv0DLrXDGRZ2tPEA&oe=6'),
(144, 'Manuel Eduardo', 'Montenegro', 'precandidato a concejal', 29, '', '0000-00-00', '', 'https://scontent.faep14-2.fna.fbcdn.net/v/t39.30808-6/273661059_245800141064257_1990454909025994020_n.png?_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=bCNUBukZTeYAX_rPmxF&_nc_ht=scontent.faep14-2.fna&oh=00_AfCjeJNp7foGsXF4QrEwyftfUjYYWaV9c6S0Rx6R9kE0fQ&oe=6'),
(145, 'Mabel irene', 'Aves', 'precandidata a intendente', 29, '', '0000-00-00', '', 'https://scontent.faep14-2.fna.fbcdn.net/v/t39.30808-6/273661059_245800141064257_1990454909025994020_n.png?_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=bCNUBukZTeYAX_rPmxF&_nc_ht=scontent.faep14-2.fna&oh=00_AfCjeJNp7foGsXF4QrEwyftfUjYYWaV9c6S0Rx6R9kE0fQ&oe=6'),
(146, 'Celeste', 'Fierro', 'Legisladora', 30, '', '0000-00-00', 'Legisladora de la Ciudad , Coordinadora juntas de la izquierda y dirigente del MST', 'https://images.pagina12.com.ar/styles/focal_3_2_960x640/public/2021-08/184630-celeste-20fierro-20fitu.jpg?h=c673cd1c&itok=85qFGB4A'),
(147, 'Alejandro', 'Bodart', 'Secretario general', 30, '', '1963-12-02', 'político argentino. Fue legislador de la Ciudad de Buenos Aires entre 2011-2015, es secretario general del Movimiento Socialista de los Trabajadores (MST) en el Frente de Izquierda y de los Trabajadores - Unidad, y coordinador de la Liga Internacional Socialista. Integra la redacción del periódico Alternativa Socialista y el portal Periodismo de Izquierda.', 'https://www.lanacion.com.ar/resizer/v2/alejandro-S3LFPJGZ3NBXFFW4LO4AASQORQ.png?auth=b2d703257576d5493d087f9b8ddc844bf3a90dcacdfc1d6eb358aaaeeb985728&width=880&height=586&quality=70&smart=true'),
(148, 'Vilma', 'Ripoll', 'dirigente', 30, 'Universidad Nacional de Rosario', '1954-04-12', 'Licenciada en enfermería por la Universidad Nacional de Rosario, trabaja como enfermera de terapia intensiva en la Unidad Coronaria del Hospital Italiano de Buenos Aires. Actualmente, integra la conducción nacional del Movimiento Socialista de los Trabajadores Nueva Izquierda (MST Nueva Izquierda), partido de orientación morenista. Además es la referente de Juntas y a la Izquierda, la agrupación nacional de mujeres del MST Nueva Izquierda.', 'https://www.lavoz.com.ar/resizer/S9KucOCMsTDqfCdQQQ_OuBBVtVU=/1024x683/smart/filters:quality(75):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/VSG46OEUKFFSPL4SAWG3Z42V4I.jpg'),
(149, 'Gabriel', 'Solano', 'dirigente', 30, '', '1974-06-04', 'Es dirigente del Partido Obrero y legislador porteño desde diciembre de 2021. Ya había ocupado la banca desde el 10 de diciembre del 2017 hasta el 10 de diciembre del 2020.', 'https://po.org.ar/wp-content/uploads/2023/05/Gabriel-Solano-2-1-e1683724365136-1536x1476.jpg'),
(150, 'Luciana', 'Echeverria', '', 30, 'Universidad Nacional de Cordoba', '1982-04-23', 'Legisladora de la Provincia de Córdoba,comunicadora, docente, feminista y ecosocialista. Docente en dos escuelas secundarias y en la Universidad pública. Licenciada y Profesora en Comunicación Social y Especialista de Nivel Superior en Educación y Medios Digitales. ', 'https://periodismoparalagente.com/wp-content/uploads/2023/04/luciana-750x375.jpg');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `partidospoliticos`
--
ALTER TABLE `partidospoliticos`
  ADD PRIMARY KEY (`partido_id`);

--
-- Indices de la tabla `politicos`
--
ALTER TABLE `politicos`
  ADD PRIMARY KEY (`politico_id`),
  ADD KEY `partido_id` (`partido_id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `partidospoliticos`
--
ALTER TABLE `partidospoliticos`
  MODIFY `partido_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT de la tabla `politicos`
--
ALTER TABLE `politicos`
  MODIFY `politico_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=151;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `politicos`
--
ALTER TABLE `politicos`
  ADD CONSTRAINT `politicos_ibfk_1` FOREIGN KEY (`partido_id`) REFERENCES `partidospoliticos` (`partido_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
